/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as TalleresRouteImport } from './routes/talleres'
import { Route as RentalRouteImport } from './routes/rental'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PreguntasFrecuentesRouteImport } from './routes/preguntas-frecuentes'
import { Route as KitPreviewRouteImport } from './routes/kit-preview'
import { Route as EstudioRouteImport } from './routes/estudio'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TalleresIndexRouteImport } from './routes/talleres.index'
import { Route as ClienteIndexRouteImport } from './routes/cliente.index'
import { Route as WorkshopsSlugRouteImport } from './routes/workshops.$slug'
import { Route as TalleresSlugRouteImport } from './routes/talleres.$slug'
import { Route as EquipoSlugRouteImport } from './routes/equipo.$slug'
import { Route as ClienteRegistroRouteImport } from './routes/cliente.registro'
import { Route as ClientePortalRouteImport } from './routes/cliente.portal'
import { Route as ClientePerfilRouteImport } from './routes/cliente.perfil'
import { Route as ClienteLoginRouteImport } from './routes/cliente.login'
import { Route as ClienteClaimRouteImport } from './routes/cliente.claim'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as AdminTalleresRouteImport } from './routes/admin/talleres'
import { Route as AdminNovedadesRouteImport } from './routes/admin/novedades'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEstudioRouteImport } from './routes/admin/estudio'
import { Route as AdminEquiposRouteImport } from './routes/admin/equipos'
import { Route as ClientePedidosIdEditarRouteImport } from './routes/cliente.pedidos.$id.editar'

const WorkshopsIndexLazyRouteImport = createFileRoute('/workshops/')()
const AdminIndexLazyRouteImport = createFileRoute('/admin/')()
const AdminUnidadesLazyRouteImport = createFileRoute('/admin/unidades')()
const AdminSolicitudesLazyRouteImport = createFileRoute('/admin/solicitudes')()
const AdminSettingsLazyRouteImport = createFileRoute('/admin/settings')()
const AdminProductorasLazyRouteImport = createFileRoute('/admin/productoras')()
const AdminPagosLazyRouteImport = createFileRoute('/admin/pagos')()
const AdminMediaLazyRouteImport = createFileRoute('/admin/media')()
const AdminMarcaLazyRouteImport = createFileRoute('/admin/marca')()
const AdminFacturasLazyRouteImport = createFileRoute('/admin/facturas')()
const AdminEstadisticasLazyRouteImport = createFileRoute(
  '/admin/estadisticas',
)()
const AdminErroresLazyRouteImport = createFileRoute('/admin/errores')()
const AdminEmailTemplatesLazyRouteImport = createFileRoute(
  '/admin/email-templates',
)()
const AdminDisenoLazyRouteImport = createFileRoute('/admin/diseno')()
const AdminDataioLazyRouteImport = createFileRoute('/admin/dataio')()
const AdminClientesLazyRouteImport = createFileRoute('/admin/clientes')()
const AdminCarritosLazyRouteImport = createFileRoute('/admin/carritos')()
const AdminTalleresIndexLazyRouteImport = createFileRoute('/admin/talleres/')()
const AdminSpecsIndexLazyRouteImport = createFileRoute('/admin/specs/')()
const AdminPedidosIndexLazyRouteImport = createFileRoute('/admin/pedidos/')()
const AdminEstudioIndexLazyRouteImport = createFileRoute('/admin/estudio/')()
const AdminEquiposIndexLazyRouteImport = createFileRoute('/admin/equipos/')()
const AdminContabilidadIndexLazyRouteImport = createFileRoute(
  '/admin/contabilidad/',
)()
const AdminSpecsDefinitionsLazyRouteImport = createFileRoute(
  '/admin/specs/definitions',
)()
const AdminPedidosNuevoLazyRouteImport = createFileRoute(
  '/admin/pedidos/nuevo',
)()
const AdminPedidosIdLazyRouteImport = createFileRoute('/admin/pedidos/$id')()
const AdminFacturacionExportacionLazyRouteImport = createFileRoute(
  '/admin/facturacion/exportacion',
)()
const AdminFacturacionEmisoresLazyRouteImport = createFileRoute(
  '/admin/facturacion/emisores',
)()
const AdminEquiposSpecsLazyRouteImport = createFileRoute(
  '/admin/equipos/specs',
)()
const AdminEquiposNuevoLazyRouteImport = createFileRoute(
  '/admin/equipos/nuevo',
)()
const AdminEquiposMarcasLazyRouteImport = createFileRoute(
  '/admin/equipos/marcas',
)()
const AdminEquiposCategoriasLazyRouteImport = createFileRoute(
  '/admin/equipos/categorias',
)()
const AdminEquiposCalidadLazyRouteImport = createFileRoute(
  '/admin/equipos/calidad',
)()
const AdminContabilidadReporteLazyRouteImport = createFileRoute(
  '/admin/contabilidad/reporte',
)()
const AdminContabilidadMovimientosLazyRouteImport = createFileRoute(
  '/admin/contabilidad/movimientos',
)()
const AdminContabilidadLiquidacionLazyRouteImport = createFileRoute(
  '/admin/contabilidad/liquidacion',
)()
const AdminContabilidadGlosarioLazyRouteImport = createFileRoute(
  '/admin/contabilidad/glosario',
)()
const AdminContabilidadCuentasLazyRouteImport = createFileRoute(
  '/admin/contabilidad/cuentas',
)()
const AdminEquiposIdEditarLazyRouteImport = createFileRoute(
  '/admin/equipos/$id/editar',
)()

const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/workshops.lazy').then((d) => d.Route))
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const TalleresRoute = TalleresRouteImport.update({
  id: '/talleres',
  path: '/talleres',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalRoute = RentalRouteImport.update({
  id: '/rental',
  path: '/rental',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasFrecuentesRoute = PreguntasFrecuentesRouteImport.update({
  id: '/preguntas-frecuentes',
  path: '/preguntas-frecuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const KitPreviewRoute = KitPreviewRouteImport.update({
  id: '/kit-preview',
  path: '/kit-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudioRoute = EstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/estudio.lazy').then((d) => d.Route))
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsIndexLazyRoute = WorkshopsIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkshopsRoute,
} as any).lazy(() =>
  import('./routes/workshops.index.lazy').then((d) => d.Route),
)
const AdminIndexLazyRoute = AdminIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/index.lazy').then((d) => d.Route))
const TalleresIndexRoute = TalleresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TalleresRoute,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClienteRoute,
} as any)
const AdminUnidadesLazyRoute = AdminUnidadesLazyRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/unidades.lazy').then((d) => d.Route),
)
const AdminSolicitudesLazyRoute = AdminSolicitudesLazyRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/solicitudes.lazy').then((d) => d.Route),
)
const AdminSettingsLazyRoute = AdminSettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/settings.lazy').then((d) => d.Route),
)
const AdminProductorasLazyRoute = AdminProductorasLazyRouteImport.update({
  id: '/productoras',
  path: '/productoras',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/productoras.lazy').then((d) => d.Route),
)
const AdminPagosLazyRoute = AdminPagosLazyRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/pagos.lazy').then((d) => d.Route))
const AdminMediaLazyRoute = AdminMediaLazyRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/media.lazy').then((d) => d.Route))
const AdminMarcaLazyRoute = AdminMarcaLazyRouteImport.update({
  id: '/marca',
  path: '/marca',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/marca.lazy').then((d) => d.Route))
const AdminFacturasLazyRoute = AdminFacturasLazyRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/facturas.lazy').then((d) => d.Route),
)
const AdminEstadisticasLazyRoute = AdminEstadisticasLazyRouteImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/estadisticas.lazy').then((d) => d.Route),
)
const AdminErroresLazyRoute = AdminErroresLazyRouteImport.update({
  id: '/errores',
  path: '/errores',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/errores.lazy').then((d) => d.Route))
const AdminEmailTemplatesLazyRoute = AdminEmailTemplatesLazyRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/email-templates.lazy').then((d) => d.Route),
)
const AdminDisenoLazyRoute = AdminDisenoLazyRouteImport.update({
  id: '/diseno',
  path: '/diseno',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/diseno.lazy').then((d) => d.Route))
const AdminDataioLazyRoute = AdminDataioLazyRouteImport.update({
  id: '/dataio',
  path: '/dataio',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/dataio.lazy').then((d) => d.Route))
const AdminClientesLazyRoute = AdminClientesLazyRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/clientes.lazy').then((d) => d.Route),
)
const AdminCarritosLazyRoute = AdminCarritosLazyRouteImport.update({
  id: '/carritos',
  path: '/carritos',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/carritos.lazy').then((d) => d.Route),
)
const WorkshopsSlugRoute = WorkshopsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkshopsRoute,
} as any).lazy(() =>
  import('./routes/workshops.$slug.lazy').then((d) => d.Route),
)
const TalleresSlugRoute = TalleresSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TalleresRoute,
} as any)
const EquipoSlugRoute = EquipoSlugRouteImport.update({
  id: '/equipo/$slug',
  path: '/equipo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRegistroRoute = ClienteRegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => ClienteRoute,
} as any)
const ClientePortalRoute = ClientePortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => ClienteRoute,
} as any)
const ClientePerfilRoute = ClientePerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteLoginRoute = ClienteLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteClaimRoute = ClienteClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => ClienteRoute,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTalleresRoute = AdminTalleresRouteImport.update({
  id: '/talleres',
  path: '/talleres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNovedadesRoute = AdminNovedadesRouteImport.update({
  id: '/novedades',
  path: '/novedades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstudioRoute = AdminEstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquiposRoute = AdminEquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTalleresIndexLazyRoute = AdminTalleresIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTalleresRoute,
} as any).lazy(() =>
  import('./routes/admin/talleres.index.lazy').then((d) => d.Route),
)
const AdminSpecsIndexLazyRoute = AdminSpecsIndexLazyRouteImport.update({
  id: '/specs/',
  path: '/specs/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/specs.index.lazy').then((d) => d.Route),
)
const AdminPedidosIndexLazyRoute = AdminPedidosIndexLazyRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/pedidos.index.lazy').then((d) => d.Route),
)
const AdminEstudioIndexLazyRoute = AdminEstudioIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEstudioRoute,
} as any).lazy(() =>
  import('./routes/admin/estudio.index.lazy').then((d) => d.Route),
)
const AdminEquiposIndexLazyRoute = AdminEquiposIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEquiposRoute,
} as any).lazy(() =>
  import('./routes/admin/equipos.index.lazy').then((d) => d.Route),
)
const AdminContabilidadIndexLazyRoute =
  AdminContabilidadIndexLazyRouteImport.update({
    id: '/contabilidad/',
    path: '/contabilidad/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/contabilidad.index.lazy').then((d) => d.Route),
  )
const AdminSpecsDefinitionsLazyRoute =
  AdminSpecsDefinitionsLazyRouteImport.update({
    id: '/specs/definitions',
    path: '/specs/definitions',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/specs.definitions.lazy').then((d) => d.Route),
  )
const AdminPedidosNuevoLazyRoute = AdminPedidosNuevoLazyRouteImport.update({
  id: '/pedidos/nuevo',
  path: '/pedidos/nuevo',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/pedidos.nuevo.lazy').then((d) => d.Route),
)
const AdminPedidosIdLazyRoute = AdminPedidosIdLazyRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/pedidos.$id.lazy').then((d) => d.Route),
)
const AdminFacturacionExportacionLazyRoute =
  AdminFacturacionExportacionLazyRouteImport.update({
    id: '/facturacion/exportacion',
    path: '/facturacion/exportacion',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/facturacion.exportacion.lazy').then((d) => d.Route),
  )
const AdminFacturacionEmisoresLazyRoute =
  AdminFacturacionEmisoresLazyRouteImport.update({
    id: '/facturacion/emisores',
    path: '/facturacion/emisores',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/facturacion.emisores.lazy').then((d) => d.Route),
  )
const AdminEquiposSpecsLazyRoute = AdminEquiposSpecsLazyRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => AdminEquiposRoute,
} as any).lazy(() =>
  import('./routes/admin/equipos.specs.lazy').then((d) => d.Route),
)
const AdminEquiposNuevoLazyRoute = AdminEquiposNuevoLazyRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => AdminEquiposRoute,
} as any).lazy(() =>
  import('./routes/admin/equipos.nuevo.lazy').then((d) => d.Route),
)
const AdminEquiposMarcasLazyRoute = AdminEquiposMarcasLazyRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => AdminEquiposRoute,
} as any).lazy(() =>
  import('./routes/admin/equipos.marcas.lazy').then((d) => d.Route),
)
const AdminEquiposCategoriasLazyRoute =
  AdminEquiposCategoriasLazyRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AdminEquiposRoute,
  } as any).lazy(() =>
    import('./routes/admin/equipos.categorias.lazy').then((d) => d.Route),
  )
const AdminEquiposCalidadLazyRoute = AdminEquiposCalidadLazyRouteImport.update({
  id: '/calidad',
  path: '/calidad',
  getParentRoute: () => AdminEquiposRoute,
} as any).lazy(() =>
  import('./routes/admin/equipos.calidad.lazy').then((d) => d.Route),
)
const AdminContabilidadReporteLazyRoute =
  AdminContabilidadReporteLazyRouteImport.update({
    id: '/contabilidad/reporte',
    path: '/contabilidad/reporte',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/contabilidad.reporte.lazy').then((d) => d.Route),
  )
const AdminContabilidadMovimientosLazyRoute =
  AdminContabilidadMovimientosLazyRouteImport.update({
    id: '/contabilidad/movimientos',
    path: '/contabilidad/movimientos',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/contabilidad.movimientos.lazy').then((d) => d.Route),
  )
const AdminContabilidadLiquidacionLazyRoute =
  AdminContabilidadLiquidacionLazyRouteImport.update({
    id: '/contabilidad/liquidacion',
    path: '/contabilidad/liquidacion',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/contabilidad.liquidacion.lazy').then((d) => d.Route),
  )
const AdminContabilidadGlosarioLazyRoute =
  AdminContabilidadGlosarioLazyRouteImport.update({
    id: '/contabilidad/glosario',
    path: '/contabilidad/glosario',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/contabilidad.glosario.lazy').then((d) => d.Route),
  )
const AdminContabilidadCuentasLazyRoute =
  AdminContabilidadCuentasLazyRouteImport.update({
    id: '/contabilidad/cuentas',
    path: '/contabilidad/cuentas',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/contabilidad.cuentas.lazy').then((d) => d.Route),
  )
const AdminEquiposIdEditarLazyRoute =
  AdminEquiposIdEditarLazyRouteImport.update({
    id: '/$id/editar',
    path: '/$id/editar',
    getParentRoute: () => AdminEquiposRoute,
  } as any).lazy(() =>
    import('./routes/admin/equipos.$id.editar.lazy').then((d) => d.Route),
  )
const ClientePedidosIdEditarRoute = ClientePedidosIdEditarRouteImport.update({
  id: '/pedidos/$id/editar',
  path: '/pedidos/$id/editar',
  getParentRoute: () => ClienteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/estudio': typeof EstudioRoute
  '/kit-preview': typeof KitPreviewRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/privacidad': typeof PrivacidadRoute
  '/rental': typeof RentalRoute
  '/talleres': typeof TalleresRouteWithChildren
  '/terminos': typeof TerminosRoute
  '/workshops': typeof WorkshopsRouteWithChildren
  '/admin/equipos': typeof AdminEquiposRouteWithChildren
  '/admin/estudio': typeof AdminEstudioRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/novedades': typeof AdminNovedadesRoute
  '/admin/talleres': typeof AdminTalleresRouteWithChildren
  '/c/$token': typeof CTokenRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/cliente/claim': typeof ClienteClaimRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/cliente/portal': typeof ClientePortalRoute
  '/cliente/registro': typeof ClienteRegistroRoute
  '/equipo/$slug': typeof EquipoSlugRoute
  '/talleres/$slug': typeof TalleresSlugRoute
  '/workshops/$slug': typeof WorkshopsSlugRoute
  '/admin/carritos': typeof AdminCarritosLazyRoute
  '/admin/clientes': typeof AdminClientesLazyRoute
  '/admin/dataio': typeof AdminDataioLazyRoute
  '/admin/diseno': typeof AdminDisenoLazyRoute
  '/admin/email-templates': typeof AdminEmailTemplatesLazyRoute
  '/admin/errores': typeof AdminErroresLazyRoute
  '/admin/estadisticas': typeof AdminEstadisticasLazyRoute
  '/admin/facturas': typeof AdminFacturasLazyRoute
  '/admin/marca': typeof AdminMarcaLazyRoute
  '/admin/media': typeof AdminMediaLazyRoute
  '/admin/pagos': typeof AdminPagosLazyRoute
  '/admin/productoras': typeof AdminProductorasLazyRoute
  '/admin/settings': typeof AdminSettingsLazyRoute
  '/admin/solicitudes': typeof AdminSolicitudesLazyRoute
  '/admin/unidades': typeof AdminUnidadesLazyRoute
  '/cliente/': typeof ClienteIndexRoute
  '/talleres/': typeof TalleresIndexRoute
  '/admin/': typeof AdminIndexLazyRoute
  '/workshops/': typeof WorkshopsIndexLazyRoute
  '/admin/contabilidad/cuentas': typeof AdminContabilidadCuentasLazyRoute
  '/admin/contabilidad/glosario': typeof AdminContabilidadGlosarioLazyRoute
  '/admin/contabilidad/liquidacion': typeof AdminContabilidadLiquidacionLazyRoute
  '/admin/contabilidad/movimientos': typeof AdminContabilidadMovimientosLazyRoute
  '/admin/contabilidad/reporte': typeof AdminContabilidadReporteLazyRoute
  '/admin/equipos/calidad': typeof AdminEquiposCalidadLazyRoute
  '/admin/equipos/categorias': typeof AdminEquiposCategoriasLazyRoute
  '/admin/equipos/marcas': typeof AdminEquiposMarcasLazyRoute
  '/admin/equipos/nuevo': typeof AdminEquiposNuevoLazyRoute
  '/admin/equipos/specs': typeof AdminEquiposSpecsLazyRoute
  '/admin/facturacion/emisores': typeof AdminFacturacionEmisoresLazyRoute
  '/admin/facturacion/exportacion': typeof AdminFacturacionExportacionLazyRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdLazyRoute
  '/admin/pedidos/nuevo': typeof AdminPedidosNuevoLazyRoute
  '/admin/specs/definitions': typeof AdminSpecsDefinitionsLazyRoute
  '/admin/contabilidad/': typeof AdminContabilidadIndexLazyRoute
  '/admin/equipos/': typeof AdminEquiposIndexLazyRoute
  '/admin/estudio/': typeof AdminEstudioIndexLazyRoute
  '/admin/pedidos/': typeof AdminPedidosIndexLazyRoute
  '/admin/specs/': typeof AdminSpecsIndexLazyRoute
  '/admin/talleres/': typeof AdminTalleresIndexLazyRoute
  '/cliente/pedidos/$id/editar': typeof ClientePedidosIdEditarRoute
  '/admin/equipos/$id/editar': typeof AdminEquiposIdEditarLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/estudio': typeof EstudioRoute
  '/kit-preview': typeof KitPreviewRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/privacidad': typeof PrivacidadRoute
  '/rental': typeof RentalRoute
  '/terminos': typeof TerminosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/novedades': typeof AdminNovedadesRoute
  '/c/$token': typeof CTokenRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/cliente/claim': typeof ClienteClaimRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/cliente/portal': typeof ClientePortalRoute
  '/cliente/registro': typeof ClienteRegistroRoute
  '/equipo/$slug': typeof EquipoSlugRoute
  '/talleres/$slug': typeof TalleresSlugRoute
  '/workshops/$slug': typeof WorkshopsSlugRoute
  '/admin/carritos': typeof AdminCarritosLazyRoute
  '/admin/clientes': typeof AdminClientesLazyRoute
  '/admin/dataio': typeof AdminDataioLazyRoute
  '/admin/diseno': typeof AdminDisenoLazyRoute
  '/admin/email-templates': typeof AdminEmailTemplatesLazyRoute
  '/admin/errores': typeof AdminErroresLazyRoute
  '/admin/estadisticas': typeof AdminEstadisticasLazyRoute
  '/admin/facturas': typeof AdminFacturasLazyRoute
  '/admin/marca': typeof AdminMarcaLazyRoute
  '/admin/media': typeof AdminMediaLazyRoute
  '/admin/pagos': typeof AdminPagosLazyRoute
  '/admin/productoras': typeof AdminProductorasLazyRoute
  '/admin/settings': typeof AdminSettingsLazyRoute
  '/admin/solicitudes': typeof AdminSolicitudesLazyRoute
  '/admin/unidades': typeof AdminUnidadesLazyRoute
  '/cliente': typeof ClienteIndexRoute
  '/talleres': typeof TalleresIndexRoute
  '/admin': typeof AdminIndexLazyRoute
  '/workshops': typeof WorkshopsIndexLazyRoute
  '/admin/contabilidad/cuentas': typeof AdminContabilidadCuentasLazyRoute
  '/admin/contabilidad/glosario': typeof AdminContabilidadGlosarioLazyRoute
  '/admin/contabilidad/liquidacion': typeof AdminContabilidadLiquidacionLazyRoute
  '/admin/contabilidad/movimientos': typeof AdminContabilidadMovimientosLazyRoute
  '/admin/contabilidad/reporte': typeof AdminContabilidadReporteLazyRoute
  '/admin/equipos/calidad': typeof AdminEquiposCalidadLazyRoute
  '/admin/equipos/categorias': typeof AdminEquiposCategoriasLazyRoute
  '/admin/equipos/marcas': typeof AdminEquiposMarcasLazyRoute
  '/admin/equipos/nuevo': typeof AdminEquiposNuevoLazyRoute
  '/admin/equipos/specs': typeof AdminEquiposSpecsLazyRoute
  '/admin/facturacion/emisores': typeof AdminFacturacionEmisoresLazyRoute
  '/admin/facturacion/exportacion': typeof AdminFacturacionExportacionLazyRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdLazyRoute
  '/admin/pedidos/nuevo': typeof AdminPedidosNuevoLazyRoute
  '/admin/specs/definitions': typeof AdminSpecsDefinitionsLazyRoute
  '/admin/contabilidad': typeof AdminContabilidadIndexLazyRoute
  '/admin/equipos': typeof AdminEquiposIndexLazyRoute
  '/admin/estudio': typeof AdminEstudioIndexLazyRoute
  '/admin/pedidos': typeof AdminPedidosIndexLazyRoute
  '/admin/specs': typeof AdminSpecsIndexLazyRoute
  '/admin/talleres': typeof AdminTalleresIndexLazyRoute
  '/cliente/pedidos/$id/editar': typeof ClientePedidosIdEditarRoute
  '/admin/equipos/$id/editar': typeof AdminEquiposIdEditarLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/estudio': typeof EstudioRoute
  '/kit-preview': typeof KitPreviewRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/privacidad': typeof PrivacidadRoute
  '/rental': typeof RentalRoute
  '/talleres': typeof TalleresRouteWithChildren
  '/terminos': typeof TerminosRoute
  '/workshops': typeof WorkshopsRouteWithChildren
  '/admin/equipos': typeof AdminEquiposRouteWithChildren
  '/admin/estudio': typeof AdminEstudioRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/novedades': typeof AdminNovedadesRoute
  '/admin/talleres': typeof AdminTalleresRouteWithChildren
  '/c/$token': typeof CTokenRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/cliente/claim': typeof ClienteClaimRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/cliente/portal': typeof ClientePortalRoute
  '/cliente/registro': typeof ClienteRegistroRoute
  '/equipo/$slug': typeof EquipoSlugRoute
  '/talleres/$slug': typeof TalleresSlugRoute
  '/workshops/$slug': typeof WorkshopsSlugRoute
  '/admin/carritos': typeof AdminCarritosLazyRoute
  '/admin/clientes': typeof AdminClientesLazyRoute
  '/admin/dataio': typeof AdminDataioLazyRoute
  '/admin/diseno': typeof AdminDisenoLazyRoute
  '/admin/email-templates': typeof AdminEmailTemplatesLazyRoute
  '/admin/errores': typeof AdminErroresLazyRoute
  '/admin/estadisticas': typeof AdminEstadisticasLazyRoute
  '/admin/facturas': typeof AdminFacturasLazyRoute
  '/admin/marca': typeof AdminMarcaLazyRoute
  '/admin/media': typeof AdminMediaLazyRoute
  '/admin/pagos': typeof AdminPagosLazyRoute
  '/admin/productoras': typeof AdminProductorasLazyRoute
  '/admin/settings': typeof AdminSettingsLazyRoute
  '/admin/solicitudes': typeof AdminSolicitudesLazyRoute
  '/admin/unidades': typeof AdminUnidadesLazyRoute
  '/cliente/': typeof ClienteIndexRoute
  '/talleres/': typeof TalleresIndexRoute
  '/admin/': typeof AdminIndexLazyRoute
  '/workshops/': typeof WorkshopsIndexLazyRoute
  '/admin/contabilidad/cuentas': typeof AdminContabilidadCuentasLazyRoute
  '/admin/contabilidad/glosario': typeof AdminContabilidadGlosarioLazyRoute
  '/admin/contabilidad/liquidacion': typeof AdminContabilidadLiquidacionLazyRoute
  '/admin/contabilidad/movimientos': typeof AdminContabilidadMovimientosLazyRoute
  '/admin/contabilidad/reporte': typeof AdminContabilidadReporteLazyRoute
  '/admin/equipos/calidad': typeof AdminEquiposCalidadLazyRoute
  '/admin/equipos/categorias': typeof AdminEquiposCategoriasLazyRoute
  '/admin/equipos/marcas': typeof AdminEquiposMarcasLazyRoute
  '/admin/equipos/nuevo': typeof AdminEquiposNuevoLazyRoute
  '/admin/equipos/specs': typeof AdminEquiposSpecsLazyRoute
  '/admin/facturacion/emisores': typeof AdminFacturacionEmisoresLazyRoute
  '/admin/facturacion/exportacion': typeof AdminFacturacionExportacionLazyRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdLazyRoute
  '/admin/pedidos/nuevo': typeof AdminPedidosNuevoLazyRoute
  '/admin/specs/definitions': typeof AdminSpecsDefinitionsLazyRoute
  '/admin/contabilidad/': typeof AdminContabilidadIndexLazyRoute
  '/admin/equipos/': typeof AdminEquiposIndexLazyRoute
  '/admin/estudio/': typeof AdminEstudioIndexLazyRoute
  '/admin/pedidos/': typeof AdminPedidosIndexLazyRoute
  '/admin/specs/': typeof AdminSpecsIndexLazyRoute
  '/admin/talleres/': typeof AdminTalleresIndexLazyRoute
  '/cliente/pedidos/$id/editar': typeof ClientePedidosIdEditarRoute
  '/admin/equipos/$id/editar': typeof AdminEquiposIdEditarLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalogo'
    | '/cliente'
    | '/estudio'
    | '/kit-preview'
    | '/preguntas-frecuentes'
    | '/privacidad'
    | '/rental'
    | '/talleres'
    | '/terminos'
    | '/workshops'
    | '/admin/equipos'
    | '/admin/estudio'
    | '/admin/login'
    | '/admin/novedades'
    | '/admin/talleres'
    | '/c/$token'
    | '/categoria/$slug'
    | '/cliente/claim'
    | '/cliente/login'
    | '/cliente/perfil'
    | '/cliente/portal'
    | '/cliente/registro'
    | '/equipo/$slug'
    | '/talleres/$slug'
    | '/workshops/$slug'
    | '/admin/carritos'
    | '/admin/clientes'
    | '/admin/dataio'
    | '/admin/diseno'
    | '/admin/email-templates'
    | '/admin/errores'
    | '/admin/estadisticas'
    | '/admin/facturas'
    | '/admin/marca'
    | '/admin/media'
    | '/admin/pagos'
    | '/admin/productoras'
    | '/admin/settings'
    | '/admin/solicitudes'
    | '/admin/unidades'
    | '/cliente/'
    | '/talleres/'
    | '/admin/'
    | '/workshops/'
    | '/admin/contabilidad/cuentas'
    | '/admin/contabilidad/glosario'
    | '/admin/contabilidad/liquidacion'
    | '/admin/contabilidad/movimientos'
    | '/admin/contabilidad/reporte'
    | '/admin/equipos/calidad'
    | '/admin/equipos/categorias'
    | '/admin/equipos/marcas'
    | '/admin/equipos/nuevo'
    | '/admin/equipos/specs'
    | '/admin/facturacion/emisores'
    | '/admin/facturacion/exportacion'
    | '/admin/pedidos/$id'
    | '/admin/pedidos/nuevo'
    | '/admin/specs/definitions'
    | '/admin/contabilidad/'
    | '/admin/equipos/'
    | '/admin/estudio/'
    | '/admin/pedidos/'
    | '/admin/specs/'
    | '/admin/talleres/'
    | '/cliente/pedidos/$id/editar'
    | '/admin/equipos/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/estudio'
    | '/kit-preview'
    | '/preguntas-frecuentes'
    | '/privacidad'
    | '/rental'
    | '/terminos'
    | '/admin/login'
    | '/admin/novedades'
    | '/c/$token'
    | '/categoria/$slug'
    | '/cliente/claim'
    | '/cliente/login'
    | '/cliente/perfil'
    | '/cliente/portal'
    | '/cliente/registro'
    | '/equipo/$slug'
    | '/talleres/$slug'
    | '/workshops/$slug'
    | '/admin/carritos'
    | '/admin/clientes'
    | '/admin/dataio'
    | '/admin/diseno'
    | '/admin/email-templates'
    | '/admin/errores'
    | '/admin/estadisticas'
    | '/admin/facturas'
    | '/admin/marca'
    | '/admin/media'
    | '/admin/pagos'
    | '/admin/productoras'
    | '/admin/settings'
    | '/admin/solicitudes'
    | '/admin/unidades'
    | '/cliente'
    | '/talleres'
    | '/admin'
    | '/workshops'
    | '/admin/contabilidad/cuentas'
    | '/admin/contabilidad/glosario'
    | '/admin/contabilidad/liquidacion'
    | '/admin/contabilidad/movimientos'
    | '/admin/contabilidad/reporte'
    | '/admin/equipos/calidad'
    | '/admin/equipos/categorias'
    | '/admin/equipos/marcas'
    | '/admin/equipos/nuevo'
    | '/admin/equipos/specs'
    | '/admin/facturacion/emisores'
    | '/admin/facturacion/exportacion'
    | '/admin/pedidos/$id'
    | '/admin/pedidos/nuevo'
    | '/admin/specs/definitions'
    | '/admin/contabilidad'
    | '/admin/equipos'
    | '/admin/estudio'
    | '/admin/pedidos'
    | '/admin/specs'
    | '/admin/talleres'
    | '/cliente/pedidos/$id/editar'
    | '/admin/equipos/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalogo'
    | '/cliente'
    | '/estudio'
    | '/kit-preview'
    | '/preguntas-frecuentes'
    | '/privacidad'
    | '/rental'
    | '/talleres'
    | '/terminos'
    | '/workshops'
    | '/admin/equipos'
    | '/admin/estudio'
    | '/admin/login'
    | '/admin/novedades'
    | '/admin/talleres'
    | '/c/$token'
    | '/categoria/$slug'
    | '/cliente/claim'
    | '/cliente/login'
    | '/cliente/perfil'
    | '/cliente/portal'
    | '/cliente/registro'
    | '/equipo/$slug'
    | '/talleres/$slug'
    | '/workshops/$slug'
    | '/admin/carritos'
    | '/admin/clientes'
    | '/admin/dataio'
    | '/admin/diseno'
    | '/admin/email-templates'
    | '/admin/errores'
    | '/admin/estadisticas'
    | '/admin/facturas'
    | '/admin/marca'
    | '/admin/media'
    | '/admin/pagos'
    | '/admin/productoras'
    | '/admin/settings'
    | '/admin/solicitudes'
    | '/admin/unidades'
    | '/cliente/'
    | '/talleres/'
    | '/admin/'
    | '/workshops/'
    | '/admin/contabilidad/cuentas'
    | '/admin/contabilidad/glosario'
    | '/admin/contabilidad/liquidacion'
    | '/admin/contabilidad/movimientos'
    | '/admin/contabilidad/reporte'
    | '/admin/equipos/calidad'
    | '/admin/equipos/categorias'
    | '/admin/equipos/marcas'
    | '/admin/equipos/nuevo'
    | '/admin/equipos/specs'
    | '/admin/facturacion/emisores'
    | '/admin/facturacion/exportacion'
    | '/admin/pedidos/$id'
    | '/admin/pedidos/nuevo'
    | '/admin/specs/definitions'
    | '/admin/contabilidad/'
    | '/admin/equipos/'
    | '/admin/estudio/'
    | '/admin/pedidos/'
    | '/admin/specs/'
    | '/admin/talleres/'
    | '/cliente/pedidos/$id/editar'
    | '/admin/equipos/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CatalogoRoute: typeof CatalogoRoute
  ClienteRoute: typeof ClienteRouteWithChildren
  EstudioRoute: typeof EstudioRoute
  KitPreviewRoute: typeof KitPreviewRoute
  PreguntasFrecuentesRoute: typeof PreguntasFrecuentesRoute
  PrivacidadRoute: typeof PrivacidadRoute
  RentalRoute: typeof RentalRoute
  TalleresRoute: typeof TalleresRouteWithChildren
  TerminosRoute: typeof TerminosRoute
  WorkshopsRoute: typeof WorkshopsRouteWithChildren
  CTokenRoute: typeof CTokenRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  EquipoSlugRoute: typeof EquipoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talleres': {
      id: '/talleres'
      path: '/talleres'
      fullPath: '/talleres'
      preLoaderRoute: typeof TalleresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental': {
      id: '/rental'
      path: '/rental'
      fullPath: '/rental'
      preLoaderRoute: typeof RentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas-frecuentes': {
      id: '/preguntas-frecuentes'
      path: '/preguntas-frecuentes'
      fullPath: '/preguntas-frecuentes'
      preLoaderRoute: typeof PreguntasFrecuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit-preview': {
      id: '/kit-preview'
      path: '/kit-preview'
      fullPath: '/kit-preview'
      preLoaderRoute: typeof KitPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudio': {
      id: '/estudio'
      path: '/estudio'
      fullPath: '/estudio'
      preLoaderRoute: typeof EstudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops/': {
      id: '/workshops/'
      path: '/'
      fullPath: '/workshops/'
      preLoaderRoute: typeof WorkshopsIndexLazyRouteImport
      parentRoute: typeof WorkshopsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/talleres/': {
      id: '/talleres/'
      path: '/'
      fullPath: '/talleres/'
      preLoaderRoute: typeof TalleresIndexRouteImport
      parentRoute: typeof TalleresRoute
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/admin/unidades': {
      id: '/admin/unidades'
      path: '/unidades'
      fullPath: '/admin/unidades'
      preLoaderRoute: typeof AdminUnidadesLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/solicitudes': {
      id: '/admin/solicitudes'
      path: '/solicitudes'
      fullPath: '/admin/solicitudes'
      preLoaderRoute: typeof AdminSolicitudesLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productoras': {
      id: '/admin/productoras'
      path: '/productoras'
      fullPath: '/admin/productoras'
      preLoaderRoute: typeof AdminProductorasLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagos': {
      id: '/admin/pagos'
      path: '/pagos'
      fullPath: '/admin/pagos'
      preLoaderRoute: typeof AdminPagosLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marca': {
      id: '/admin/marca'
      path: '/marca'
      fullPath: '/admin/marca'
      preLoaderRoute: typeof AdminMarcaLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facturas': {
      id: '/admin/facturas'
      path: '/facturas'
      fullPath: '/admin/facturas'
      preLoaderRoute: typeof AdminFacturasLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estadisticas': {
      id: '/admin/estadisticas'
      path: '/estadisticas'
      fullPath: '/admin/estadisticas'
      preLoaderRoute: typeof AdminEstadisticasLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/errores': {
      id: '/admin/errores'
      path: '/errores'
      fullPath: '/admin/errores'
      preLoaderRoute: typeof AdminErroresLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-templates': {
      id: '/admin/email-templates'
      path: '/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AdminEmailTemplatesLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diseno': {
      id: '/admin/diseno'
      path: '/diseno'
      fullPath: '/admin/diseno'
      preLoaderRoute: typeof AdminDisenoLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dataio': {
      id: '/admin/dataio'
      path: '/dataio'
      fullPath: '/admin/dataio'
      preLoaderRoute: typeof AdminDataioLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/carritos': {
      id: '/admin/carritos'
      path: '/carritos'
      fullPath: '/admin/carritos'
      preLoaderRoute: typeof AdminCarritosLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/workshops/$slug': {
      id: '/workshops/$slug'
      path: '/$slug'
      fullPath: '/workshops/$slug'
      preLoaderRoute: typeof WorkshopsSlugRouteImport
      parentRoute: typeof WorkshopsRoute
    }
    '/talleres/$slug': {
      id: '/talleres/$slug'
      path: '/$slug'
      fullPath: '/talleres/$slug'
      preLoaderRoute: typeof TalleresSlugRouteImport
      parentRoute: typeof TalleresRoute
    }
    '/equipo/$slug': {
      id: '/equipo/$slug'
      path: '/equipo/$slug'
      fullPath: '/equipo/$slug'
      preLoaderRoute: typeof EquipoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/registro': {
      id: '/cliente/registro'
      path: '/registro'
      fullPath: '/cliente/registro'
      preLoaderRoute: typeof ClienteRegistroRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/portal': {
      id: '/cliente/portal'
      path: '/portal'
      fullPath: '/cliente/portal'
      preLoaderRoute: typeof ClientePortalRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/perfil': {
      id: '/cliente/perfil'
      path: '/perfil'
      fullPath: '/cliente/perfil'
      preLoaderRoute: typeof ClientePerfilRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/login': {
      id: '/cliente/login'
      path: '/login'
      fullPath: '/cliente/login'
      preLoaderRoute: typeof ClienteLoginRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/claim': {
      id: '/cliente/claim'
      path: '/claim'
      fullPath: '/cliente/claim'
      preLoaderRoute: typeof ClienteClaimRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/talleres': {
      id: '/admin/talleres'
      path: '/talleres'
      fullPath: '/admin/talleres'
      preLoaderRoute: typeof AdminTalleresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/novedades': {
      id: '/admin/novedades'
      path: '/novedades'
      fullPath: '/admin/novedades'
      preLoaderRoute: typeof AdminNovedadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estudio': {
      id: '/admin/estudio'
      path: '/estudio'
      fullPath: '/admin/estudio'
      preLoaderRoute: typeof AdminEstudioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipos': {
      id: '/admin/equipos'
      path: '/equipos'
      fullPath: '/admin/equipos'
      preLoaderRoute: typeof AdminEquiposRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/talleres/': {
      id: '/admin/talleres/'
      path: '/'
      fullPath: '/admin/talleres/'
      preLoaderRoute: typeof AdminTalleresIndexLazyRouteImport
      parentRoute: typeof AdminTalleresRoute
    }
    '/admin/specs/': {
      id: '/admin/specs/'
      path: '/specs'
      fullPath: '/admin/specs/'
      preLoaderRoute: typeof AdminSpecsIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos/': {
      id: '/admin/pedidos/'
      path: '/pedidos'
      fullPath: '/admin/pedidos/'
      preLoaderRoute: typeof AdminPedidosIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estudio/': {
      id: '/admin/estudio/'
      path: '/'
      fullPath: '/admin/estudio/'
      preLoaderRoute: typeof AdminEstudioIndexLazyRouteImport
      parentRoute: typeof AdminEstudioRoute
    }
    '/admin/equipos/': {
      id: '/admin/equipos/'
      path: '/'
      fullPath: '/admin/equipos/'
      preLoaderRoute: typeof AdminEquiposIndexLazyRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
    '/admin/contabilidad/': {
      id: '/admin/contabilidad/'
      path: '/contabilidad'
      fullPath: '/admin/contabilidad/'
      preLoaderRoute: typeof AdminContabilidadIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/specs/definitions': {
      id: '/admin/specs/definitions'
      path: '/specs/definitions'
      fullPath: '/admin/specs/definitions'
      preLoaderRoute: typeof AdminSpecsDefinitionsLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos/nuevo': {
      id: '/admin/pedidos/nuevo'
      path: '/pedidos/nuevo'
      fullPath: '/admin/pedidos/nuevo'
      preLoaderRoute: typeof AdminPedidosNuevoLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos/$id': {
      id: '/admin/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AdminPedidosIdLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facturacion/exportacion': {
      id: '/admin/facturacion/exportacion'
      path: '/facturacion/exportacion'
      fullPath: '/admin/facturacion/exportacion'
      preLoaderRoute: typeof AdminFacturacionExportacionLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facturacion/emisores': {
      id: '/admin/facturacion/emisores'
      path: '/facturacion/emisores'
      fullPath: '/admin/facturacion/emisores'
      preLoaderRoute: typeof AdminFacturacionEmisoresLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipos/specs': {
      id: '/admin/equipos/specs'
      path: '/specs'
      fullPath: '/admin/equipos/specs'
      preLoaderRoute: typeof AdminEquiposSpecsLazyRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
    '/admin/equipos/nuevo': {
      id: '/admin/equipos/nuevo'
      path: '/nuevo'
      fullPath: '/admin/equipos/nuevo'
      preLoaderRoute: typeof AdminEquiposNuevoLazyRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
    '/admin/equipos/marcas': {
      id: '/admin/equipos/marcas'
      path: '/marcas'
      fullPath: '/admin/equipos/marcas'
      preLoaderRoute: typeof AdminEquiposMarcasLazyRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
    '/admin/equipos/categorias': {
      id: '/admin/equipos/categorias'
      path: '/categorias'
      fullPath: '/admin/equipos/categorias'
      preLoaderRoute: typeof AdminEquiposCategoriasLazyRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
    '/admin/equipos/calidad': {
      id: '/admin/equipos/calidad'
      path: '/calidad'
      fullPath: '/admin/equipos/calidad'
      preLoaderRoute: typeof AdminEquiposCalidadLazyRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
    '/admin/contabilidad/reporte': {
      id: '/admin/contabilidad/reporte'
      path: '/contabilidad/reporte'
      fullPath: '/admin/contabilidad/reporte'
      preLoaderRoute: typeof AdminContabilidadReporteLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contabilidad/movimientos': {
      id: '/admin/contabilidad/movimientos'
      path: '/contabilidad/movimientos'
      fullPath: '/admin/contabilidad/movimientos'
      preLoaderRoute: typeof AdminContabilidadMovimientosLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contabilidad/liquidacion': {
      id: '/admin/contabilidad/liquidacion'
      path: '/contabilidad/liquidacion'
      fullPath: '/admin/contabilidad/liquidacion'
      preLoaderRoute: typeof AdminContabilidadLiquidacionLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contabilidad/glosario': {
      id: '/admin/contabilidad/glosario'
      path: '/contabilidad/glosario'
      fullPath: '/admin/contabilidad/glosario'
      preLoaderRoute: typeof AdminContabilidadGlosarioLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contabilidad/cuentas': {
      id: '/admin/contabilidad/cuentas'
      path: '/contabilidad/cuentas'
      fullPath: '/admin/contabilidad/cuentas'
      preLoaderRoute: typeof AdminContabilidadCuentasLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipos/$id/editar': {
      id: '/admin/equipos/$id/editar'
      path: '/$id/editar'
      fullPath: '/admin/equipos/$id/editar'
      preLoaderRoute: typeof AdminEquiposIdEditarLazyRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
    '/cliente/pedidos/$id/editar': {
      id: '/cliente/pedidos/$id/editar'
      path: '/pedidos/$id/editar'
      fullPath: '/cliente/pedidos/$id/editar'
      preLoaderRoute: typeof ClientePedidosIdEditarRouteImport
      parentRoute: typeof ClienteRoute
    }
  }
}

interface AdminEquiposRouteChildren {
  AdminEquiposCalidadLazyRoute: typeof AdminEquiposCalidadLazyRoute
  AdminEquiposCategoriasLazyRoute: typeof AdminEquiposCategoriasLazyRoute
  AdminEquiposMarcasLazyRoute: typeof AdminEquiposMarcasLazyRoute
  AdminEquiposNuevoLazyRoute: typeof AdminEquiposNuevoLazyRoute
  AdminEquiposSpecsLazyRoute: typeof AdminEquiposSpecsLazyRoute
  AdminEquiposIndexLazyRoute: typeof AdminEquiposIndexLazyRoute
  AdminEquiposIdEditarLazyRoute: typeof AdminEquiposIdEditarLazyRoute
}

const AdminEquiposRouteChildren: AdminEquiposRouteChildren = {
  AdminEquiposCalidadLazyRoute: AdminEquiposCalidadLazyRoute,
  AdminEquiposCategoriasLazyRoute: AdminEquiposCategoriasLazyRoute,
  AdminEquiposMarcasLazyRoute: AdminEquiposMarcasLazyRoute,
  AdminEquiposNuevoLazyRoute: AdminEquiposNuevoLazyRoute,
  AdminEquiposSpecsLazyRoute: AdminEquiposSpecsLazyRoute,
  AdminEquiposIndexLazyRoute: AdminEquiposIndexLazyRoute,
  AdminEquiposIdEditarLazyRoute: AdminEquiposIdEditarLazyRoute,
}

const AdminEquiposRouteWithChildren = AdminEquiposRoute._addFileChildren(
  AdminEquiposRouteChildren,
)

interface AdminEstudioRouteChildren {
  AdminEstudioIndexLazyRoute: typeof AdminEstudioIndexLazyRoute
}

const AdminEstudioRouteChildren: AdminEstudioRouteChildren = {
  AdminEstudioIndexLazyRoute: AdminEstudioIndexLazyRoute,
}

const AdminEstudioRouteWithChildren = AdminEstudioRoute._addFileChildren(
  AdminEstudioRouteChildren,
)

interface AdminTalleresRouteChildren {
  AdminTalleresIndexLazyRoute: typeof AdminTalleresIndexLazyRoute
}

const AdminTalleresRouteChildren: AdminTalleresRouteChildren = {
  AdminTalleresIndexLazyRoute: AdminTalleresIndexLazyRoute,
}

const AdminTalleresRouteWithChildren = AdminTalleresRoute._addFileChildren(
  AdminTalleresRouteChildren,
)

interface AdminRouteChildren {
  AdminEquiposRoute: typeof AdminEquiposRouteWithChildren
  AdminEstudioRoute: typeof AdminEstudioRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNovedadesRoute: typeof AdminNovedadesRoute
  AdminTalleresRoute: typeof AdminTalleresRouteWithChildren
  AdminCarritosLazyRoute: typeof AdminCarritosLazyRoute
  AdminClientesLazyRoute: typeof AdminClientesLazyRoute
  AdminDataioLazyRoute: typeof AdminDataioLazyRoute
  AdminDisenoLazyRoute: typeof AdminDisenoLazyRoute
  AdminEmailTemplatesLazyRoute: typeof AdminEmailTemplatesLazyRoute
  AdminErroresLazyRoute: typeof AdminErroresLazyRoute
  AdminEstadisticasLazyRoute: typeof AdminEstadisticasLazyRoute
  AdminFacturasLazyRoute: typeof AdminFacturasLazyRoute
  AdminMarcaLazyRoute: typeof AdminMarcaLazyRoute
  AdminMediaLazyRoute: typeof AdminMediaLazyRoute
  AdminPagosLazyRoute: typeof AdminPagosLazyRoute
  AdminProductorasLazyRoute: typeof AdminProductorasLazyRoute
  AdminSettingsLazyRoute: typeof AdminSettingsLazyRoute
  AdminSolicitudesLazyRoute: typeof AdminSolicitudesLazyRoute
  AdminUnidadesLazyRoute: typeof AdminUnidadesLazyRoute
  AdminIndexLazyRoute: typeof AdminIndexLazyRoute
  AdminContabilidadCuentasLazyRoute: typeof AdminContabilidadCuentasLazyRoute
  AdminContabilidadGlosarioLazyRoute: typeof AdminContabilidadGlosarioLazyRoute
  AdminContabilidadLiquidacionLazyRoute: typeof AdminContabilidadLiquidacionLazyRoute
  AdminContabilidadMovimientosLazyRoute: typeof AdminContabilidadMovimientosLazyRoute
  AdminContabilidadReporteLazyRoute: typeof AdminContabilidadReporteLazyRoute
  AdminFacturacionEmisoresLazyRoute: typeof AdminFacturacionEmisoresLazyRoute
  AdminFacturacionExportacionLazyRoute: typeof AdminFacturacionExportacionLazyRoute
  AdminPedidosIdLazyRoute: typeof AdminPedidosIdLazyRoute
  AdminPedidosNuevoLazyRoute: typeof AdminPedidosNuevoLazyRoute
  AdminSpecsDefinitionsLazyRoute: typeof AdminSpecsDefinitionsLazyRoute
  AdminContabilidadIndexLazyRoute: typeof AdminContabilidadIndexLazyRoute
  AdminPedidosIndexLazyRoute: typeof AdminPedidosIndexLazyRoute
  AdminSpecsIndexLazyRoute: typeof AdminSpecsIndexLazyRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEquiposRoute: AdminEquiposRouteWithChildren,
  AdminEstudioRoute: AdminEstudioRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminNovedadesRoute: AdminNovedadesRoute,
  AdminTalleresRoute: AdminTalleresRouteWithChildren,
  AdminCarritosLazyRoute: AdminCarritosLazyRoute,
  AdminClientesLazyRoute: AdminClientesLazyRoute,
  AdminDataioLazyRoute: AdminDataioLazyRoute,
  AdminDisenoLazyRoute: AdminDisenoLazyRoute,
  AdminEmailTemplatesLazyRoute: AdminEmailTemplatesLazyRoute,
  AdminErroresLazyRoute: AdminErroresLazyRoute,
  AdminEstadisticasLazyRoute: AdminEstadisticasLazyRoute,
  AdminFacturasLazyRoute: AdminFacturasLazyRoute,
  AdminMarcaLazyRoute: AdminMarcaLazyRoute,
  AdminMediaLazyRoute: AdminMediaLazyRoute,
  AdminPagosLazyRoute: AdminPagosLazyRoute,
  AdminProductorasLazyRoute: AdminProductorasLazyRoute,
  AdminSettingsLazyRoute: AdminSettingsLazyRoute,
  AdminSolicitudesLazyRoute: AdminSolicitudesLazyRoute,
  AdminUnidadesLazyRoute: AdminUnidadesLazyRoute,
  AdminIndexLazyRoute: AdminIndexLazyRoute,
  AdminContabilidadCuentasLazyRoute: AdminContabilidadCuentasLazyRoute,
  AdminContabilidadGlosarioLazyRoute: AdminContabilidadGlosarioLazyRoute,
  AdminContabilidadLiquidacionLazyRoute: AdminContabilidadLiquidacionLazyRoute,
  AdminContabilidadMovimientosLazyRoute: AdminContabilidadMovimientosLazyRoute,
  AdminContabilidadReporteLazyRoute: AdminContabilidadReporteLazyRoute,
  AdminFacturacionEmisoresLazyRoute: AdminFacturacionEmisoresLazyRoute,
  AdminFacturacionExportacionLazyRoute: AdminFacturacionExportacionLazyRoute,
  AdminPedidosIdLazyRoute: AdminPedidosIdLazyRoute,
  AdminPedidosNuevoLazyRoute: AdminPedidosNuevoLazyRoute,
  AdminSpecsDefinitionsLazyRoute: AdminSpecsDefinitionsLazyRoute,
  AdminContabilidadIndexLazyRoute: AdminContabilidadIndexLazyRoute,
  AdminPedidosIndexLazyRoute: AdminPedidosIndexLazyRoute,
  AdminSpecsIndexLazyRoute: AdminSpecsIndexLazyRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClienteRouteChildren {
  ClienteClaimRoute: typeof ClienteClaimRoute
  ClienteLoginRoute: typeof ClienteLoginRoute
  ClientePerfilRoute: typeof ClientePerfilRoute
  ClientePortalRoute: typeof ClientePortalRoute
  ClienteRegistroRoute: typeof ClienteRegistroRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
  ClientePedidosIdEditarRoute: typeof ClientePedidosIdEditarRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteClaimRoute: ClienteClaimRoute,
  ClienteLoginRoute: ClienteLoginRoute,
  ClientePerfilRoute: ClientePerfilRoute,
  ClientePortalRoute: ClientePortalRoute,
  ClienteRegistroRoute: ClienteRegistroRoute,
  ClienteIndexRoute: ClienteIndexRoute,
  ClientePedidosIdEditarRoute: ClientePedidosIdEditarRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

interface TalleresRouteChildren {
  TalleresSlugRoute: typeof TalleresSlugRoute
  TalleresIndexRoute: typeof TalleresIndexRoute
}

const TalleresRouteChildren: TalleresRouteChildren = {
  TalleresSlugRoute: TalleresSlugRoute,
  TalleresIndexRoute: TalleresIndexRoute,
}

const TalleresRouteWithChildren = TalleresRoute._addFileChildren(
  TalleresRouteChildren,
)

interface WorkshopsRouteChildren {
  WorkshopsSlugRoute: typeof WorkshopsSlugRoute
  WorkshopsIndexLazyRoute: typeof WorkshopsIndexLazyRoute
}

const WorkshopsRouteChildren: WorkshopsRouteChildren = {
  WorkshopsSlugRoute: WorkshopsSlugRoute,
  WorkshopsIndexLazyRoute: WorkshopsIndexLazyRoute,
}

const WorkshopsRouteWithChildren = WorkshopsRoute._addFileChildren(
  WorkshopsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CatalogoRoute: CatalogoRoute,
  ClienteRoute: ClienteRouteWithChildren,
  EstudioRoute: EstudioRoute,
  KitPreviewRoute: KitPreviewRoute,
  PreguntasFrecuentesRoute: PreguntasFrecuentesRoute,
  PrivacidadRoute: PrivacidadRoute,
  RentalRoute: RentalRoute,
  TalleresRoute: TalleresRouteWithChildren,
  TerminosRoute: TerminosRoute,
  WorkshopsRoute: WorkshopsRouteWithChildren,
  CTokenRoute: CTokenRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  EquipoSlugRoute: EquipoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
