/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PreguntasFrecuentesRouteImport } from './routes/preguntas-frecuentes'
import { Route as EstudioRouteImport } from './routes/estudio'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClienteIndexRouteImport } from './routes/cliente.index'
import { Route as EquipoSlugRouteImport } from './routes/equipo.$slug'
import { Route as ClienteRegistroRouteImport } from './routes/cliente.registro'
import { Route as ClientePortalRouteImport } from './routes/cliente.portal'
import { Route as ClientePerfilRouteImport } from './routes/cliente.perfil'
import { Route as ClienteLoginRouteImport } from './routes/cliente.login'
import { Route as AdminNovedadesRouteImport } from './routes/admin/novedades'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEquiposRouteImport } from './routes/admin/equipos'
import { Route as AdminEquiposEtiquetasRouteImport } from './routes/admin/equipos.etiquetas'

const AdminIndexLazyRouteImport = createFileRoute('/admin/')()
const AdminUnidadesLazyRouteImport = createFileRoute('/admin/unidades')()
const AdminSettingsLazyRouteImport = createFileRoute('/admin/settings')()
const AdminHoyLazyRouteImport = createFileRoute('/admin/hoy')()
const AdminGearCompatibilityLazyRouteImport = createFileRoute(
  '/admin/gear-compatibility',
)()
const AdminEstadisticasLazyRouteImport = createFileRoute(
  '/admin/estadisticas',
)()
const AdminDisenoLazyRouteImport = createFileRoute('/admin/diseno')()
const AdminClientesLazyRouteImport = createFileRoute('/admin/clientes')()
const AdminCalendarioLazyRouteImport = createFileRoute('/admin/calendario')()
const AdminPedidosIndexLazyRouteImport = createFileRoute('/admin/pedidos/')()
const AdminEquiposIndexLazyRouteImport = createFileRoute('/admin/equipos/')()
const AdminSpecsPropuestasLazyRouteImport = createFileRoute(
  '/admin/specs/propuestas',
)()
const AdminSpecsObservatorioLazyRouteImport = createFileRoute(
  '/admin/specs/observatorio',
)()
const AdminSpecsLegacyLazyRouteImport = createFileRoute('/admin/specs/legacy')()
const AdminSpecsFamiliasLazyRouteImport = createFileRoute(
  '/admin/specs/familias',
)()
const AdminSpecsDefinitionsLazyRouteImport = createFileRoute(
  '/admin/specs/definitions',
)()
const AdminSpecsDedupLazyRouteImport = createFileRoute('/admin/specs/dedup')()
const AdminPedidosNuevoLazyRouteImport = createFileRoute(
  '/admin/pedidos/nuevo',
)()
const AdminPedidosIdLazyRouteImport = createFileRoute('/admin/pedidos/$id')()
const AdminEquiposValidacionLazyRouteImport = createFileRoute(
  '/admin/equipos/validacion',
)()
const AdminEquiposSpecsLazyRouteImport = createFileRoute(
  '/admin/equipos/specs',
)()
const AdminEquiposMarcasLazyRouteImport = createFileRoute(
  '/admin/equipos/marcas',
)()
const AdminEquiposClasificarLazyRouteImport = createFileRoute(
  '/admin/equipos/clasificar',
)()
const AdminEquiposCategoriasLazyRouteImport = createFileRoute(
  '/admin/equipos/categorias',
)()
const AdminEquiposCalidadLazyRouteImport = createFileRoute(
  '/admin/equipos/calidad',
)()

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasFrecuentesRoute = PreguntasFrecuentesRouteImport.update({
  id: '/preguntas-frecuentes',
  path: '/preguntas-frecuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudioRoute = EstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexLazyRoute = AdminIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/index.lazy').then((d) => d.Route))
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClienteRoute,
} as any)
const AdminUnidadesLazyRoute = AdminUnidadesLazyRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/unidades.lazy').then((d) => d.Route),
)
const AdminSettingsLazyRoute = AdminSettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/settings.lazy').then((d) => d.Route),
)
const AdminHoyLazyRoute = AdminHoyLazyRouteImport.update({
  id: '/hoy',
  path: '/hoy',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/hoy.lazy').then((d) => d.Route))
const AdminGearCompatibilityLazyRoute =
  AdminGearCompatibilityLazyRouteImport.update({
    id: '/gear-compatibility',
    path: '/gear-compatibility',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/gear-compatibility.lazy').then((d) => d.Route),
  )
const AdminEstadisticasLazyRoute = AdminEstadisticasLazyRouteImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/estadisticas.lazy').then((d) => d.Route),
)
const AdminDisenoLazyRoute = AdminDisenoLazyRouteImport.update({
  id: '/diseno',
  path: '/diseno',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/diseno.lazy').then((d) => d.Route))
const AdminClientesLazyRoute = AdminClientesLazyRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/clientes.lazy').then((d) => d.Route),
)
const AdminCalendarioLazyRoute = AdminCalendarioLazyRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/calendario.lazy').then((d) => d.Route),
)
const EquipoSlugRoute = EquipoSlugRouteImport.update({
  id: '/equipo/$slug',
  path: '/equipo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRegistroRoute = ClienteRegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => ClienteRoute,
} as any)
const ClientePortalRoute = ClientePortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => ClienteRoute,
} as any)
const ClientePerfilRoute = ClientePerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteLoginRoute = ClienteLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ClienteRoute,
} as any)
const AdminNovedadesRoute = AdminNovedadesRouteImport.update({
  id: '/novedades',
  path: '/novedades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquiposRoute = AdminEquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosIndexLazyRoute = AdminPedidosIndexLazyRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/pedidos.index.lazy').then((d) => d.Route),
)
const AdminEquiposIndexLazyRoute = AdminEquiposIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEquiposRoute,
} as any).lazy(() =>
  import('./routes/admin/equipos.index.lazy').then((d) => d.Route),
)
const AdminSpecsPropuestasLazyRoute =
  AdminSpecsPropuestasLazyRouteImport.update({
    id: '/specs/propuestas',
    path: '/specs/propuestas',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/specs.propuestas.lazy').then((d) => d.Route),
  )
const AdminSpecsObservatorioLazyRoute =
  AdminSpecsObservatorioLazyRouteImport.update({
    id: '/specs/observatorio',
    path: '/specs/observatorio',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/specs.observatorio.lazy').then((d) => d.Route),
  )
const AdminSpecsLegacyLazyRoute = AdminSpecsLegacyLazyRouteImport.update({
  id: '/specs/legacy',
  path: '/specs/legacy',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/specs.legacy.lazy').then((d) => d.Route),
)
const AdminSpecsFamiliasLazyRoute = AdminSpecsFamiliasLazyRouteImport.update({
  id: '/specs/familias',
  path: '/specs/familias',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/specs.familias.lazy').then((d) => d.Route),
)
const AdminSpecsDefinitionsLazyRoute =
  AdminSpecsDefinitionsLazyRouteImport.update({
    id: '/specs/definitions',
    path: '/specs/definitions',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/specs.definitions.lazy').then((d) => d.Route),
  )
const AdminSpecsDedupLazyRoute = AdminSpecsDedupLazyRouteImport.update({
  id: '/specs/dedup',
  path: '/specs/dedup',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/specs.dedup.lazy').then((d) => d.Route),
)
const AdminPedidosNuevoLazyRoute = AdminPedidosNuevoLazyRouteImport.update({
  id: '/pedidos/nuevo',
  path: '/pedidos/nuevo',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/pedidos.nuevo.lazy').then((d) => d.Route),
)
const AdminPedidosIdLazyRoute = AdminPedidosIdLazyRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/pedidos.$id.lazy').then((d) => d.Route),
)
const AdminEquiposValidacionLazyRoute =
  AdminEquiposValidacionLazyRouteImport.update({
    id: '/validacion',
    path: '/validacion',
    getParentRoute: () => AdminEquiposRoute,
  } as any).lazy(() =>
    import('./routes/admin/equipos.validacion.lazy').then((d) => d.Route),
  )
const AdminEquiposSpecsLazyRoute = AdminEquiposSpecsLazyRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => AdminEquiposRoute,
} as any).lazy(() =>
  import('./routes/admin/equipos.specs.lazy').then((d) => d.Route),
)
const AdminEquiposMarcasLazyRoute = AdminEquiposMarcasLazyRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => AdminEquiposRoute,
} as any).lazy(() =>
  import('./routes/admin/equipos.marcas.lazy').then((d) => d.Route),
)
const AdminEquiposClasificarLazyRoute =
  AdminEquiposClasificarLazyRouteImport.update({
    id: '/clasificar',
    path: '/clasificar',
    getParentRoute: () => AdminEquiposRoute,
  } as any).lazy(() =>
    import('./routes/admin/equipos.clasificar.lazy').then((d) => d.Route),
  )
const AdminEquiposCategoriasLazyRoute =
  AdminEquiposCategoriasLazyRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AdminEquiposRoute,
  } as any).lazy(() =>
    import('./routes/admin/equipos.categorias.lazy').then((d) => d.Route),
  )
const AdminEquiposCalidadLazyRoute = AdminEquiposCalidadLazyRouteImport.update({
  id: '/calidad',
  path: '/calidad',
  getParentRoute: () => AdminEquiposRoute,
} as any).lazy(() =>
  import('./routes/admin/equipos.calidad.lazy').then((d) => d.Route),
)
const AdminEquiposEtiquetasRoute = AdminEquiposEtiquetasRouteImport.update({
  id: '/etiquetas',
  path: '/etiquetas',
  getParentRoute: () => AdminEquiposRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/estudio': typeof EstudioRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/admin/equipos': typeof AdminEquiposRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/novedades': typeof AdminNovedadesRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/cliente/portal': typeof ClientePortalRoute
  '/cliente/registro': typeof ClienteRegistroRoute
  '/equipo/$slug': typeof EquipoSlugRoute
  '/admin/calendario': typeof AdminCalendarioLazyRoute
  '/admin/clientes': typeof AdminClientesLazyRoute
  '/admin/diseno': typeof AdminDisenoLazyRoute
  '/admin/estadisticas': typeof AdminEstadisticasLazyRoute
  '/admin/gear-compatibility': typeof AdminGearCompatibilityLazyRoute
  '/admin/hoy': typeof AdminHoyLazyRoute
  '/admin/settings': typeof AdminSettingsLazyRoute
  '/admin/unidades': typeof AdminUnidadesLazyRoute
  '/cliente/': typeof ClienteIndexRoute
  '/admin/': typeof AdminIndexLazyRoute
  '/admin/equipos/etiquetas': typeof AdminEquiposEtiquetasRoute
  '/admin/equipos/calidad': typeof AdminEquiposCalidadLazyRoute
  '/admin/equipos/categorias': typeof AdminEquiposCategoriasLazyRoute
  '/admin/equipos/clasificar': typeof AdminEquiposClasificarLazyRoute
  '/admin/equipos/marcas': typeof AdminEquiposMarcasLazyRoute
  '/admin/equipos/specs': typeof AdminEquiposSpecsLazyRoute
  '/admin/equipos/validacion': typeof AdminEquiposValidacionLazyRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdLazyRoute
  '/admin/pedidos/nuevo': typeof AdminPedidosNuevoLazyRoute
  '/admin/specs/dedup': typeof AdminSpecsDedupLazyRoute
  '/admin/specs/definitions': typeof AdminSpecsDefinitionsLazyRoute
  '/admin/specs/familias': typeof AdminSpecsFamiliasLazyRoute
  '/admin/specs/legacy': typeof AdminSpecsLegacyLazyRoute
  '/admin/specs/observatorio': typeof AdminSpecsObservatorioLazyRoute
  '/admin/specs/propuestas': typeof AdminSpecsPropuestasLazyRoute
  '/admin/equipos/': typeof AdminEquiposIndexLazyRoute
  '/admin/pedidos/': typeof AdminPedidosIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/estudio': typeof EstudioRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/novedades': typeof AdminNovedadesRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/cliente/portal': typeof ClientePortalRoute
  '/cliente/registro': typeof ClienteRegistroRoute
  '/equipo/$slug': typeof EquipoSlugRoute
  '/admin/calendario': typeof AdminCalendarioLazyRoute
  '/admin/clientes': typeof AdminClientesLazyRoute
  '/admin/diseno': typeof AdminDisenoLazyRoute
  '/admin/estadisticas': typeof AdminEstadisticasLazyRoute
  '/admin/gear-compatibility': typeof AdminGearCompatibilityLazyRoute
  '/admin/hoy': typeof AdminHoyLazyRoute
  '/admin/settings': typeof AdminSettingsLazyRoute
  '/admin/unidades': typeof AdminUnidadesLazyRoute
  '/cliente': typeof ClienteIndexRoute
  '/admin': typeof AdminIndexLazyRoute
  '/admin/equipos/etiquetas': typeof AdminEquiposEtiquetasRoute
  '/admin/equipos/calidad': typeof AdminEquiposCalidadLazyRoute
  '/admin/equipos/categorias': typeof AdminEquiposCategoriasLazyRoute
  '/admin/equipos/clasificar': typeof AdminEquiposClasificarLazyRoute
  '/admin/equipos/marcas': typeof AdminEquiposMarcasLazyRoute
  '/admin/equipos/specs': typeof AdminEquiposSpecsLazyRoute
  '/admin/equipos/validacion': typeof AdminEquiposValidacionLazyRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdLazyRoute
  '/admin/pedidos/nuevo': typeof AdminPedidosNuevoLazyRoute
  '/admin/specs/dedup': typeof AdminSpecsDedupLazyRoute
  '/admin/specs/definitions': typeof AdminSpecsDefinitionsLazyRoute
  '/admin/specs/familias': typeof AdminSpecsFamiliasLazyRoute
  '/admin/specs/legacy': typeof AdminSpecsLegacyLazyRoute
  '/admin/specs/observatorio': typeof AdminSpecsObservatorioLazyRoute
  '/admin/specs/propuestas': typeof AdminSpecsPropuestasLazyRoute
  '/admin/equipos': typeof AdminEquiposIndexLazyRoute
  '/admin/pedidos': typeof AdminPedidosIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/estudio': typeof EstudioRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/admin/equipos': typeof AdminEquiposRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/novedades': typeof AdminNovedadesRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/cliente/portal': typeof ClientePortalRoute
  '/cliente/registro': typeof ClienteRegistroRoute
  '/equipo/$slug': typeof EquipoSlugRoute
  '/admin/calendario': typeof AdminCalendarioLazyRoute
  '/admin/clientes': typeof AdminClientesLazyRoute
  '/admin/diseno': typeof AdminDisenoLazyRoute
  '/admin/estadisticas': typeof AdminEstadisticasLazyRoute
  '/admin/gear-compatibility': typeof AdminGearCompatibilityLazyRoute
  '/admin/hoy': typeof AdminHoyLazyRoute
  '/admin/settings': typeof AdminSettingsLazyRoute
  '/admin/unidades': typeof AdminUnidadesLazyRoute
  '/cliente/': typeof ClienteIndexRoute
  '/admin/': typeof AdminIndexLazyRoute
  '/admin/equipos/etiquetas': typeof AdminEquiposEtiquetasRoute
  '/admin/equipos/calidad': typeof AdminEquiposCalidadLazyRoute
  '/admin/equipos/categorias': typeof AdminEquiposCategoriasLazyRoute
  '/admin/equipos/clasificar': typeof AdminEquiposClasificarLazyRoute
  '/admin/equipos/marcas': typeof AdminEquiposMarcasLazyRoute
  '/admin/equipos/specs': typeof AdminEquiposSpecsLazyRoute
  '/admin/equipos/validacion': typeof AdminEquiposValidacionLazyRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdLazyRoute
  '/admin/pedidos/nuevo': typeof AdminPedidosNuevoLazyRoute
  '/admin/specs/dedup': typeof AdminSpecsDedupLazyRoute
  '/admin/specs/definitions': typeof AdminSpecsDefinitionsLazyRoute
  '/admin/specs/familias': typeof AdminSpecsFamiliasLazyRoute
  '/admin/specs/legacy': typeof AdminSpecsLegacyLazyRoute
  '/admin/specs/observatorio': typeof AdminSpecsObservatorioLazyRoute
  '/admin/specs/propuestas': typeof AdminSpecsPropuestasLazyRoute
  '/admin/equipos/': typeof AdminEquiposIndexLazyRoute
  '/admin/pedidos/': typeof AdminPedidosIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalogo'
    | '/cliente'
    | '/estudio'
    | '/preguntas-frecuentes'
    | '/privacidad'
    | '/terminos'
    | '/admin/equipos'
    | '/admin/login'
    | '/admin/novedades'
    | '/cliente/login'
    | '/cliente/perfil'
    | '/cliente/portal'
    | '/cliente/registro'
    | '/equipo/$slug'
    | '/admin/calendario'
    | '/admin/clientes'
    | '/admin/diseno'
    | '/admin/estadisticas'
    | '/admin/gear-compatibility'
    | '/admin/hoy'
    | '/admin/settings'
    | '/admin/unidades'
    | '/cliente/'
    | '/admin/'
    | '/admin/equipos/etiquetas'
    | '/admin/equipos/calidad'
    | '/admin/equipos/categorias'
    | '/admin/equipos/clasificar'
    | '/admin/equipos/marcas'
    | '/admin/equipos/specs'
    | '/admin/equipos/validacion'
    | '/admin/pedidos/$id'
    | '/admin/pedidos/nuevo'
    | '/admin/specs/dedup'
    | '/admin/specs/definitions'
    | '/admin/specs/familias'
    | '/admin/specs/legacy'
    | '/admin/specs/observatorio'
    | '/admin/specs/propuestas'
    | '/admin/equipos/'
    | '/admin/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/estudio'
    | '/preguntas-frecuentes'
    | '/privacidad'
    | '/terminos'
    | '/admin/login'
    | '/admin/novedades'
    | '/cliente/login'
    | '/cliente/perfil'
    | '/cliente/portal'
    | '/cliente/registro'
    | '/equipo/$slug'
    | '/admin/calendario'
    | '/admin/clientes'
    | '/admin/diseno'
    | '/admin/estadisticas'
    | '/admin/gear-compatibility'
    | '/admin/hoy'
    | '/admin/settings'
    | '/admin/unidades'
    | '/cliente'
    | '/admin'
    | '/admin/equipos/etiquetas'
    | '/admin/equipos/calidad'
    | '/admin/equipos/categorias'
    | '/admin/equipos/clasificar'
    | '/admin/equipos/marcas'
    | '/admin/equipos/specs'
    | '/admin/equipos/validacion'
    | '/admin/pedidos/$id'
    | '/admin/pedidos/nuevo'
    | '/admin/specs/dedup'
    | '/admin/specs/definitions'
    | '/admin/specs/familias'
    | '/admin/specs/legacy'
    | '/admin/specs/observatorio'
    | '/admin/specs/propuestas'
    | '/admin/equipos'
    | '/admin/pedidos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalogo'
    | '/cliente'
    | '/estudio'
    | '/preguntas-frecuentes'
    | '/privacidad'
    | '/terminos'
    | '/admin/equipos'
    | '/admin/login'
    | '/admin/novedades'
    | '/cliente/login'
    | '/cliente/perfil'
    | '/cliente/portal'
    | '/cliente/registro'
    | '/equipo/$slug'
    | '/admin/calendario'
    | '/admin/clientes'
    | '/admin/diseno'
    | '/admin/estadisticas'
    | '/admin/gear-compatibility'
    | '/admin/hoy'
    | '/admin/settings'
    | '/admin/unidades'
    | '/cliente/'
    | '/admin/'
    | '/admin/equipos/etiquetas'
    | '/admin/equipos/calidad'
    | '/admin/equipos/categorias'
    | '/admin/equipos/clasificar'
    | '/admin/equipos/marcas'
    | '/admin/equipos/specs'
    | '/admin/equipos/validacion'
    | '/admin/pedidos/$id'
    | '/admin/pedidos/nuevo'
    | '/admin/specs/dedup'
    | '/admin/specs/definitions'
    | '/admin/specs/familias'
    | '/admin/specs/legacy'
    | '/admin/specs/observatorio'
    | '/admin/specs/propuestas'
    | '/admin/equipos/'
    | '/admin/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CatalogoRoute: typeof CatalogoRoute
  ClienteRoute: typeof ClienteRouteWithChildren
  EstudioRoute: typeof EstudioRoute
  PreguntasFrecuentesRoute: typeof PreguntasFrecuentesRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TerminosRoute: typeof TerminosRoute
  EquipoSlugRoute: typeof EquipoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas-frecuentes': {
      id: '/preguntas-frecuentes'
      path: '/preguntas-frecuentes'
      fullPath: '/preguntas-frecuentes'
      preLoaderRoute: typeof PreguntasFrecuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudio': {
      id: '/estudio'
      path: '/estudio'
      fullPath: '/estudio'
      preLoaderRoute: typeof EstudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/admin/unidades': {
      id: '/admin/unidades'
      path: '/unidades'
      fullPath: '/admin/unidades'
      preLoaderRoute: typeof AdminUnidadesLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hoy': {
      id: '/admin/hoy'
      path: '/hoy'
      fullPath: '/admin/hoy'
      preLoaderRoute: typeof AdminHoyLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gear-compatibility': {
      id: '/admin/gear-compatibility'
      path: '/gear-compatibility'
      fullPath: '/admin/gear-compatibility'
      preLoaderRoute: typeof AdminGearCompatibilityLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estadisticas': {
      id: '/admin/estadisticas'
      path: '/estadisticas'
      fullPath: '/admin/estadisticas'
      preLoaderRoute: typeof AdminEstadisticasLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diseno': {
      id: '/admin/diseno'
      path: '/diseno'
      fullPath: '/admin/diseno'
      preLoaderRoute: typeof AdminDisenoLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendario': {
      id: '/admin/calendario'
      path: '/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AdminCalendarioLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/equipo/$slug': {
      id: '/equipo/$slug'
      path: '/equipo/$slug'
      fullPath: '/equipo/$slug'
      preLoaderRoute: typeof EquipoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/registro': {
      id: '/cliente/registro'
      path: '/registro'
      fullPath: '/cliente/registro'
      preLoaderRoute: typeof ClienteRegistroRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/portal': {
      id: '/cliente/portal'
      path: '/portal'
      fullPath: '/cliente/portal'
      preLoaderRoute: typeof ClientePortalRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/perfil': {
      id: '/cliente/perfil'
      path: '/perfil'
      fullPath: '/cliente/perfil'
      preLoaderRoute: typeof ClientePerfilRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/login': {
      id: '/cliente/login'
      path: '/login'
      fullPath: '/cliente/login'
      preLoaderRoute: typeof ClienteLoginRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/admin/novedades': {
      id: '/admin/novedades'
      path: '/novedades'
      fullPath: '/admin/novedades'
      preLoaderRoute: typeof AdminNovedadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipos': {
      id: '/admin/equipos'
      path: '/equipos'
      fullPath: '/admin/equipos'
      preLoaderRoute: typeof AdminEquiposRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos/': {
      id: '/admin/pedidos/'
      path: '/pedidos'
      fullPath: '/admin/pedidos/'
      preLoaderRoute: typeof AdminPedidosIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipos/': {
      id: '/admin/equipos/'
      path: '/'
      fullPath: '/admin/equipos/'
      preLoaderRoute: typeof AdminEquiposIndexLazyRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
    '/admin/specs/propuestas': {
      id: '/admin/specs/propuestas'
      path: '/specs/propuestas'
      fullPath: '/admin/specs/propuestas'
      preLoaderRoute: typeof AdminSpecsPropuestasLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/specs/observatorio': {
      id: '/admin/specs/observatorio'
      path: '/specs/observatorio'
      fullPath: '/admin/specs/observatorio'
      preLoaderRoute: typeof AdminSpecsObservatorioLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/specs/legacy': {
      id: '/admin/specs/legacy'
      path: '/specs/legacy'
      fullPath: '/admin/specs/legacy'
      preLoaderRoute: typeof AdminSpecsLegacyLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/specs/familias': {
      id: '/admin/specs/familias'
      path: '/specs/familias'
      fullPath: '/admin/specs/familias'
      preLoaderRoute: typeof AdminSpecsFamiliasLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/specs/definitions': {
      id: '/admin/specs/definitions'
      path: '/specs/definitions'
      fullPath: '/admin/specs/definitions'
      preLoaderRoute: typeof AdminSpecsDefinitionsLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/specs/dedup': {
      id: '/admin/specs/dedup'
      path: '/specs/dedup'
      fullPath: '/admin/specs/dedup'
      preLoaderRoute: typeof AdminSpecsDedupLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos/nuevo': {
      id: '/admin/pedidos/nuevo'
      path: '/pedidos/nuevo'
      fullPath: '/admin/pedidos/nuevo'
      preLoaderRoute: typeof AdminPedidosNuevoLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos/$id': {
      id: '/admin/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AdminPedidosIdLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipos/validacion': {
      id: '/admin/equipos/validacion'
      path: '/validacion'
      fullPath: '/admin/equipos/validacion'
      preLoaderRoute: typeof AdminEquiposValidacionLazyRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
    '/admin/equipos/specs': {
      id: '/admin/equipos/specs'
      path: '/specs'
      fullPath: '/admin/equipos/specs'
      preLoaderRoute: typeof AdminEquiposSpecsLazyRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
    '/admin/equipos/marcas': {
      id: '/admin/equipos/marcas'
      path: '/marcas'
      fullPath: '/admin/equipos/marcas'
      preLoaderRoute: typeof AdminEquiposMarcasLazyRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
    '/admin/equipos/clasificar': {
      id: '/admin/equipos/clasificar'
      path: '/clasificar'
      fullPath: '/admin/equipos/clasificar'
      preLoaderRoute: typeof AdminEquiposClasificarLazyRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
    '/admin/equipos/categorias': {
      id: '/admin/equipos/categorias'
      path: '/categorias'
      fullPath: '/admin/equipos/categorias'
      preLoaderRoute: typeof AdminEquiposCategoriasLazyRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
    '/admin/equipos/calidad': {
      id: '/admin/equipos/calidad'
      path: '/calidad'
      fullPath: '/admin/equipos/calidad'
      preLoaderRoute: typeof AdminEquiposCalidadLazyRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
    '/admin/equipos/etiquetas': {
      id: '/admin/equipos/etiquetas'
      path: '/etiquetas'
      fullPath: '/admin/equipos/etiquetas'
      preLoaderRoute: typeof AdminEquiposEtiquetasRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
  }
}

interface AdminEquiposRouteChildren {
  AdminEquiposEtiquetasRoute: typeof AdminEquiposEtiquetasRoute
  AdminEquiposCalidadLazyRoute: typeof AdminEquiposCalidadLazyRoute
  AdminEquiposCategoriasLazyRoute: typeof AdminEquiposCategoriasLazyRoute
  AdminEquiposClasificarLazyRoute: typeof AdminEquiposClasificarLazyRoute
  AdminEquiposMarcasLazyRoute: typeof AdminEquiposMarcasLazyRoute
  AdminEquiposSpecsLazyRoute: typeof AdminEquiposSpecsLazyRoute
  AdminEquiposValidacionLazyRoute: typeof AdminEquiposValidacionLazyRoute
  AdminEquiposIndexLazyRoute: typeof AdminEquiposIndexLazyRoute
}

const AdminEquiposRouteChildren: AdminEquiposRouteChildren = {
  AdminEquiposEtiquetasRoute: AdminEquiposEtiquetasRoute,
  AdminEquiposCalidadLazyRoute: AdminEquiposCalidadLazyRoute,
  AdminEquiposCategoriasLazyRoute: AdminEquiposCategoriasLazyRoute,
  AdminEquiposClasificarLazyRoute: AdminEquiposClasificarLazyRoute,
  AdminEquiposMarcasLazyRoute: AdminEquiposMarcasLazyRoute,
  AdminEquiposSpecsLazyRoute: AdminEquiposSpecsLazyRoute,
  AdminEquiposValidacionLazyRoute: AdminEquiposValidacionLazyRoute,
  AdminEquiposIndexLazyRoute: AdminEquiposIndexLazyRoute,
}

const AdminEquiposRouteWithChildren = AdminEquiposRoute._addFileChildren(
  AdminEquiposRouteChildren,
)

interface AdminRouteChildren {
  AdminEquiposRoute: typeof AdminEquiposRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNovedadesRoute: typeof AdminNovedadesRoute
  AdminCalendarioLazyRoute: typeof AdminCalendarioLazyRoute
  AdminClientesLazyRoute: typeof AdminClientesLazyRoute
  AdminDisenoLazyRoute: typeof AdminDisenoLazyRoute
  AdminEstadisticasLazyRoute: typeof AdminEstadisticasLazyRoute
  AdminGearCompatibilityLazyRoute: typeof AdminGearCompatibilityLazyRoute
  AdminHoyLazyRoute: typeof AdminHoyLazyRoute
  AdminSettingsLazyRoute: typeof AdminSettingsLazyRoute
  AdminUnidadesLazyRoute: typeof AdminUnidadesLazyRoute
  AdminIndexLazyRoute: typeof AdminIndexLazyRoute
  AdminPedidosIdLazyRoute: typeof AdminPedidosIdLazyRoute
  AdminPedidosNuevoLazyRoute: typeof AdminPedidosNuevoLazyRoute
  AdminSpecsDedupLazyRoute: typeof AdminSpecsDedupLazyRoute
  AdminSpecsDefinitionsLazyRoute: typeof AdminSpecsDefinitionsLazyRoute
  AdminSpecsFamiliasLazyRoute: typeof AdminSpecsFamiliasLazyRoute
  AdminSpecsLegacyLazyRoute: typeof AdminSpecsLegacyLazyRoute
  AdminSpecsObservatorioLazyRoute: typeof AdminSpecsObservatorioLazyRoute
  AdminSpecsPropuestasLazyRoute: typeof AdminSpecsPropuestasLazyRoute
  AdminPedidosIndexLazyRoute: typeof AdminPedidosIndexLazyRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEquiposRoute: AdminEquiposRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminNovedadesRoute: AdminNovedadesRoute,
  AdminCalendarioLazyRoute: AdminCalendarioLazyRoute,
  AdminClientesLazyRoute: AdminClientesLazyRoute,
  AdminDisenoLazyRoute: AdminDisenoLazyRoute,
  AdminEstadisticasLazyRoute: AdminEstadisticasLazyRoute,
  AdminGearCompatibilityLazyRoute: AdminGearCompatibilityLazyRoute,
  AdminHoyLazyRoute: AdminHoyLazyRoute,
  AdminSettingsLazyRoute: AdminSettingsLazyRoute,
  AdminUnidadesLazyRoute: AdminUnidadesLazyRoute,
  AdminIndexLazyRoute: AdminIndexLazyRoute,
  AdminPedidosIdLazyRoute: AdminPedidosIdLazyRoute,
  AdminPedidosNuevoLazyRoute: AdminPedidosNuevoLazyRoute,
  AdminSpecsDedupLazyRoute: AdminSpecsDedupLazyRoute,
  AdminSpecsDefinitionsLazyRoute: AdminSpecsDefinitionsLazyRoute,
  AdminSpecsFamiliasLazyRoute: AdminSpecsFamiliasLazyRoute,
  AdminSpecsLegacyLazyRoute: AdminSpecsLegacyLazyRoute,
  AdminSpecsObservatorioLazyRoute: AdminSpecsObservatorioLazyRoute,
  AdminSpecsPropuestasLazyRoute: AdminSpecsPropuestasLazyRoute,
  AdminPedidosIndexLazyRoute: AdminPedidosIndexLazyRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClienteRouteChildren {
  ClienteLoginRoute: typeof ClienteLoginRoute
  ClientePerfilRoute: typeof ClientePerfilRoute
  ClientePortalRoute: typeof ClientePortalRoute
  ClienteRegistroRoute: typeof ClienteRegistroRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteLoginRoute: ClienteLoginRoute,
  ClientePerfilRoute: ClientePerfilRoute,
  ClientePortalRoute: ClientePortalRoute,
  ClienteRegistroRoute: ClienteRegistroRoute,
  ClienteIndexRoute: ClienteIndexRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CatalogoRoute: CatalogoRoute,
  ClienteRoute: ClienteRouteWithChildren,
  EstudioRoute: EstudioRoute,
  PreguntasFrecuentesRoute: PreguntasFrecuentesRoute,
  PrivacidadRoute: PrivacidadRoute,
  TerminosRoute: TerminosRoute,
  EquipoSlugRoute: EquipoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
