/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EstudioRouteImport } from './routes/estudio'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClienteIndexRouteImport } from './routes/cliente.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ClienteRegistroRouteImport } from './routes/cliente.registro'
import { Route as ClientePortalRouteImport } from './routes/cliente.portal'
import { Route as ClienteLoginRouteImport } from './routes/cliente.login'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEstadisticasRouteImport } from './routes/admin/estadisticas'
import { Route as AdminEquiposRouteImport } from './routes/admin/equipos'
import { Route as AdminClientesRouteImport } from './routes/admin/clientes'
import { Route as AdminCalendarioRouteImport } from './routes/admin/calendario'
import { Route as AdminPedidosIndexRouteImport } from './routes/admin/pedidos.index'
import { Route as AdminEquiposIndexRouteImport } from './routes/admin/equipos.index'
import { Route as AdminPedidosNuevoRouteImport } from './routes/admin/pedidos.nuevo'
import { Route as AdminPedidosIdRouteImport } from './routes/admin/pedidos.$id'
import { Route as AdminEquiposValidacionRouteImport } from './routes/admin/equipos.validacion'
import { Route as AdminEquiposSpecsRouteImport } from './routes/admin/equipos.specs'
import { Route as AdminEquiposMarcasRouteImport } from './routes/admin/equipos.marcas'
import { Route as AdminEquiposEtiquetasRouteImport } from './routes/admin/equipos.etiquetas'
import { Route as AdminEquiposClasificarRouteImport } from './routes/admin/equipos.clasificar'
import { Route as AdminEquiposCategoriasRouteImport } from './routes/admin/equipos.categorias'

const EstudioRoute = EstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClienteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ClienteRegistroRoute = ClienteRegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => ClienteRoute,
} as any)
const ClientePortalRoute = ClientePortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteLoginRoute = ClienteLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ClienteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstadisticasRoute = AdminEstadisticasRouteImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquiposRoute = AdminEquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarioRoute = AdminCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosIndexRoute = AdminPedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquiposIndexRoute = AdminEquiposIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEquiposRoute,
} as any)
const AdminPedidosNuevoRoute = AdminPedidosNuevoRouteImport.update({
  id: '/pedidos/nuevo',
  path: '/pedidos/nuevo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosIdRoute = AdminPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquiposValidacionRoute = AdminEquiposValidacionRouteImport.update({
  id: '/validacion',
  path: '/validacion',
  getParentRoute: () => AdminEquiposRoute,
} as any)
const AdminEquiposSpecsRoute = AdminEquiposSpecsRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => AdminEquiposRoute,
} as any)
const AdminEquiposMarcasRoute = AdminEquiposMarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => AdminEquiposRoute,
} as any)
const AdminEquiposEtiquetasRoute = AdminEquiposEtiquetasRouteImport.update({
  id: '/etiquetas',
  path: '/etiquetas',
  getParentRoute: () => AdminEquiposRoute,
} as any)
const AdminEquiposClasificarRoute = AdminEquiposClasificarRouteImport.update({
  id: '/clasificar',
  path: '/clasificar',
  getParentRoute: () => AdminEquiposRoute,
} as any)
const AdminEquiposCategoriasRoute = AdminEquiposCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminEquiposRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/estudio': typeof EstudioRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/equipos': typeof AdminEquiposRouteWithChildren
  '/admin/estadisticas': typeof AdminEstadisticasRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/cliente/portal': typeof ClientePortalRoute
  '/cliente/registro': typeof ClienteRegistroRoute
  '/admin/': typeof AdminIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/admin/equipos/categorias': typeof AdminEquiposCategoriasRoute
  '/admin/equipos/clasificar': typeof AdminEquiposClasificarRoute
  '/admin/equipos/etiquetas': typeof AdminEquiposEtiquetasRoute
  '/admin/equipos/marcas': typeof AdminEquiposMarcasRoute
  '/admin/equipos/specs': typeof AdminEquiposSpecsRoute
  '/admin/equipos/validacion': typeof AdminEquiposValidacionRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/pedidos/nuevo': typeof AdminPedidosNuevoRoute
  '/admin/equipos/': typeof AdminEquiposIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estudio': typeof EstudioRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/estadisticas': typeof AdminEstadisticasRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/cliente/portal': typeof ClientePortalRoute
  '/cliente/registro': typeof ClienteRegistroRoute
  '/admin': typeof AdminIndexRoute
  '/cliente': typeof ClienteIndexRoute
  '/admin/equipos/categorias': typeof AdminEquiposCategoriasRoute
  '/admin/equipos/clasificar': typeof AdminEquiposClasificarRoute
  '/admin/equipos/etiquetas': typeof AdminEquiposEtiquetasRoute
  '/admin/equipos/marcas': typeof AdminEquiposMarcasRoute
  '/admin/equipos/specs': typeof AdminEquiposSpecsRoute
  '/admin/equipos/validacion': typeof AdminEquiposValidacionRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/pedidos/nuevo': typeof AdminPedidosNuevoRoute
  '/admin/equipos': typeof AdminEquiposIndexRoute
  '/admin/pedidos': typeof AdminPedidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/estudio': typeof EstudioRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/equipos': typeof AdminEquiposRouteWithChildren
  '/admin/estadisticas': typeof AdminEstadisticasRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/cliente/portal': typeof ClientePortalRoute
  '/cliente/registro': typeof ClienteRegistroRoute
  '/admin/': typeof AdminIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/admin/equipos/categorias': typeof AdminEquiposCategoriasRoute
  '/admin/equipos/clasificar': typeof AdminEquiposClasificarRoute
  '/admin/equipos/etiquetas': typeof AdminEquiposEtiquetasRoute
  '/admin/equipos/marcas': typeof AdminEquiposMarcasRoute
  '/admin/equipos/specs': typeof AdminEquiposSpecsRoute
  '/admin/equipos/validacion': typeof AdminEquiposValidacionRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/pedidos/nuevo': typeof AdminPedidosNuevoRoute
  '/admin/equipos/': typeof AdminEquiposIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cliente'
    | '/estudio'
    | '/admin/calendario'
    | '/admin/clientes'
    | '/admin/equipos'
    | '/admin/estadisticas'
    | '/admin/login'
    | '/admin/settings'
    | '/cliente/login'
    | '/cliente/portal'
    | '/cliente/registro'
    | '/admin/'
    | '/cliente/'
    | '/admin/equipos/categorias'
    | '/admin/equipos/clasificar'
    | '/admin/equipos/etiquetas'
    | '/admin/equipos/marcas'
    | '/admin/equipos/specs'
    | '/admin/equipos/validacion'
    | '/admin/pedidos/$id'
    | '/admin/pedidos/nuevo'
    | '/admin/equipos/'
    | '/admin/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/estudio'
    | '/admin/calendario'
    | '/admin/clientes'
    | '/admin/estadisticas'
    | '/admin/login'
    | '/admin/settings'
    | '/cliente/login'
    | '/cliente/portal'
    | '/cliente/registro'
    | '/admin'
    | '/cliente'
    | '/admin/equipos/categorias'
    | '/admin/equipos/clasificar'
    | '/admin/equipos/etiquetas'
    | '/admin/equipos/marcas'
    | '/admin/equipos/specs'
    | '/admin/equipos/validacion'
    | '/admin/pedidos/$id'
    | '/admin/pedidos/nuevo'
    | '/admin/equipos'
    | '/admin/pedidos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cliente'
    | '/estudio'
    | '/admin/calendario'
    | '/admin/clientes'
    | '/admin/equipos'
    | '/admin/estadisticas'
    | '/admin/login'
    | '/admin/settings'
    | '/cliente/login'
    | '/cliente/portal'
    | '/cliente/registro'
    | '/admin/'
    | '/cliente/'
    | '/admin/equipos/categorias'
    | '/admin/equipos/clasificar'
    | '/admin/equipos/etiquetas'
    | '/admin/equipos/marcas'
    | '/admin/equipos/specs'
    | '/admin/equipos/validacion'
    | '/admin/pedidos/$id'
    | '/admin/pedidos/nuevo'
    | '/admin/equipos/'
    | '/admin/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClienteRoute: typeof ClienteRouteWithChildren
  EstudioRoute: typeof EstudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/estudio': {
      id: '/estudio'
      path: '/estudio'
      fullPath: '/estudio'
      preLoaderRoute: typeof EstudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/cliente/registro': {
      id: '/cliente/registro'
      path: '/registro'
      fullPath: '/cliente/registro'
      preLoaderRoute: typeof ClienteRegistroRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/portal': {
      id: '/cliente/portal'
      path: '/portal'
      fullPath: '/cliente/portal'
      preLoaderRoute: typeof ClientePortalRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/login': {
      id: '/cliente/login'
      path: '/login'
      fullPath: '/cliente/login'
      preLoaderRoute: typeof ClienteLoginRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estadisticas': {
      id: '/admin/estadisticas'
      path: '/estadisticas'
      fullPath: '/admin/estadisticas'
      preLoaderRoute: typeof AdminEstadisticasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipos': {
      id: '/admin/equipos'
      path: '/equipos'
      fullPath: '/admin/equipos'
      preLoaderRoute: typeof AdminEquiposRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendario': {
      id: '/admin/calendario'
      path: '/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AdminCalendarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos/': {
      id: '/admin/pedidos/'
      path: '/pedidos'
      fullPath: '/admin/pedidos/'
      preLoaderRoute: typeof AdminPedidosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipos/': {
      id: '/admin/equipos/'
      path: '/'
      fullPath: '/admin/equipos/'
      preLoaderRoute: typeof AdminEquiposIndexRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
    '/admin/pedidos/nuevo': {
      id: '/admin/pedidos/nuevo'
      path: '/pedidos/nuevo'
      fullPath: '/admin/pedidos/nuevo'
      preLoaderRoute: typeof AdminPedidosNuevoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos/$id': {
      id: '/admin/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AdminPedidosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipos/validacion': {
      id: '/admin/equipos/validacion'
      path: '/validacion'
      fullPath: '/admin/equipos/validacion'
      preLoaderRoute: typeof AdminEquiposValidacionRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
    '/admin/equipos/specs': {
      id: '/admin/equipos/specs'
      path: '/specs'
      fullPath: '/admin/equipos/specs'
      preLoaderRoute: typeof AdminEquiposSpecsRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
    '/admin/equipos/marcas': {
      id: '/admin/equipos/marcas'
      path: '/marcas'
      fullPath: '/admin/equipos/marcas'
      preLoaderRoute: typeof AdminEquiposMarcasRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
    '/admin/equipos/etiquetas': {
      id: '/admin/equipos/etiquetas'
      path: '/etiquetas'
      fullPath: '/admin/equipos/etiquetas'
      preLoaderRoute: typeof AdminEquiposEtiquetasRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
    '/admin/equipos/clasificar': {
      id: '/admin/equipos/clasificar'
      path: '/clasificar'
      fullPath: '/admin/equipos/clasificar'
      preLoaderRoute: typeof AdminEquiposClasificarRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
    '/admin/equipos/categorias': {
      id: '/admin/equipos/categorias'
      path: '/categorias'
      fullPath: '/admin/equipos/categorias'
      preLoaderRoute: typeof AdminEquiposCategoriasRouteImport
      parentRoute: typeof AdminEquiposRoute
    }
  }
}

interface AdminEquiposRouteChildren {
  AdminEquiposCategoriasRoute: typeof AdminEquiposCategoriasRoute
  AdminEquiposClasificarRoute: typeof AdminEquiposClasificarRoute
  AdminEquiposEtiquetasRoute: typeof AdminEquiposEtiquetasRoute
  AdminEquiposMarcasRoute: typeof AdminEquiposMarcasRoute
  AdminEquiposSpecsRoute: typeof AdminEquiposSpecsRoute
  AdminEquiposValidacionRoute: typeof AdminEquiposValidacionRoute
  AdminEquiposIndexRoute: typeof AdminEquiposIndexRoute
}

const AdminEquiposRouteChildren: AdminEquiposRouteChildren = {
  AdminEquiposCategoriasRoute: AdminEquiposCategoriasRoute,
  AdminEquiposClasificarRoute: AdminEquiposClasificarRoute,
  AdminEquiposEtiquetasRoute: AdminEquiposEtiquetasRoute,
  AdminEquiposMarcasRoute: AdminEquiposMarcasRoute,
  AdminEquiposSpecsRoute: AdminEquiposSpecsRoute,
  AdminEquiposValidacionRoute: AdminEquiposValidacionRoute,
  AdminEquiposIndexRoute: AdminEquiposIndexRoute,
}

const AdminEquiposRouteWithChildren = AdminEquiposRoute._addFileChildren(
  AdminEquiposRouteChildren,
)

interface AdminRouteChildren {
  AdminCalendarioRoute: typeof AdminCalendarioRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminEquiposRoute: typeof AdminEquiposRouteWithChildren
  AdminEstadisticasRoute: typeof AdminEstadisticasRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPedidosIdRoute: typeof AdminPedidosIdRoute
  AdminPedidosNuevoRoute: typeof AdminPedidosNuevoRoute
  AdminPedidosIndexRoute: typeof AdminPedidosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalendarioRoute: AdminCalendarioRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminEquiposRoute: AdminEquiposRouteWithChildren,
  AdminEstadisticasRoute: AdminEstadisticasRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPedidosIdRoute: AdminPedidosIdRoute,
  AdminPedidosNuevoRoute: AdminPedidosNuevoRoute,
  AdminPedidosIndexRoute: AdminPedidosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClienteRouteChildren {
  ClienteLoginRoute: typeof ClienteLoginRoute
  ClientePortalRoute: typeof ClientePortalRoute
  ClienteRegistroRoute: typeof ClienteRegistroRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteLoginRoute: ClienteLoginRoute,
  ClientePortalRoute: ClientePortalRoute,
  ClienteRegistroRoute: ClienteRegistroRoute,
  ClienteIndexRoute: ClienteIndexRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClienteRoute: ClienteRouteWithChildren,
  EstudioRoute: EstudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
